version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: warehouse_postgres
    environment:
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_pass
      POSTGRES_DB: warehouse_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U warehouse_user -d warehouse_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - warehouse_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warehouse_api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_DATABASE_HOST: postgres
      APP_DATABASE_PORT: 5432
      APP_DATABASE_USER: warehouse_user
      APP_DATABASE_PASSWORD: warehouse_pass
      APP_DATABASE_DBNAME: warehouse_db
      APP_SERVER_HOST: 0.0.0.0
      APP_SERVER_PORT: 8080
      APP_JWT_SECRET: 8a0j/yucdFNFI6RhtSqAC6Pu0J/lLUbBMaS9maODAZw=
    networks:
      - warehouse_network
    restart: unless-stopped

volumes:
  postgres_data:


networks:
  warehouse_network:
    driver: bridge
